name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.12
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.12
  - applaunchservices=0.2.1
  - argh=0.26.2
  - astroid=2.4.2
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - autopep8=1.5.3
  - babel=2.8.0
  - backcall=0.2.0
  - beautifulsoup4=4.9.1
  - bleach=3.1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.5.0
  - clyent=1.2.2
  - conda=4.8.3
  - conda-build=3.19.2
  - conda-env=2.6.0
  - conda-package-handling=1.6.0
  - conda-verify=3.1.1
  - cryptography=2.9.2
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.9
  - filelock=3.0.12
  - flake8=3.8.3
  - freetype=2.10.2
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.65.0
  - glob2=0.7
  - icu=64.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intervaltree=3.0.2
  - ipycytoscape=1.0.2
  - ipykernel=5.3.2
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.17.1
  - jinja2=2.11.2
  - jpeg=9d
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.5
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab_server=1.2.0
  - keyring=21.2.1
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblief=0.9.0
  - libllvm9=9.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - navigator-updater=0.2.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.1
  - notebook=6.0.3
  - nspr=4.20
  - nss=3.47
  - numpy=1.18.5
  - numpydoc=1.1.0
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathtools=0.1.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py-lief=0.9.0
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pydocstyle=5.0.2
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pylint=2.5.3
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.34.1
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qdarkstyle=2.8.1
  - qt=5.12.5
  - qtawesome=0.7.2
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.24.0
  - ripgrep=12.1.1
  - rope=0.17.0
  - rtree=0.9.4
  - ruamel_yaml=0.15.80
  - send2trash=1.5.0
  - setuptools=49.2.0
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - spectate=0.4.1
  - sphinx=3.1.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.4
  - spyder-kernels=1.9.2
  - sqlite=3.32.3
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - traittypes=0.2.1
  - typed-ast=1.4.1
  - ujson=1.35
  - urllib3=1.25.9
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=2.0.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.29.0
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - ipympl==0.5.6
    - nodejs==0.1.1
    - optional-django==0.1.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
prefix: /Users/Nicolas/anaconda3
